name: CD

on:
  push:
    branches: [ "main", "staging", "development" ]

  workflow_dispatch:
    inputs:
      environment:
        description: 'Select deployment environment'
        required: true
        type: choice
        options:
          - development
          - staging
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    env:
      ENVIRONMENT: ${{ github.ref_name }}
      working-directory: ./app

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Echo env
        run: echo ${{ secrets.ACCESSKEY }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: pnpm install
        working-directory: ${{ env.working-directory }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build application
        run: pnpm run build
        working-directory: ${{ env.working-directory }}

      - name: Deploy to AWS S3
        run: aws s3 sync build {{ secrets.AWS_S3_URL }}
        working-directory: ${{ env.working-directory }}

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/index.html"
